import { useState, useEffect } from 'react'
import StartScreen from './components/StartScreen'
import CategoryScreen from './components/CategoryScreen'
import ResultScreen from './components/ResultScreen'
import { processVoiceQuery } from './services/api'

// Audio URLs for voice guidance (will be generated by Polly or use local fallbacks)
const AUDIO_PROMPTS = {
  welcome: '/audio/welcome.mp3',
  category_prompt: '/audio/category_prompt.mp3',
}

export default function App() {
  const [screen, setScreen] = useState('start')
  const [category, setCategory] = useState(null)
  const [schemeData, setSchemeData] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [audioUrl, setAudioUrl] = useState(null)

  // Play welcome audio on app load
  useEffect(() => {
    playWelcomeAudio()
  }, [])

  const playWelcomeAudio = () => {
    // Using Web Speech API as fallback for demo
    const utterance = new SpeechSynthesisUtterance('Namaste! Mic dabaiye aur boliye')
    utterance.lang = 'hi-IN'
    utterance.rate = 0.9
    window.speechSynthesis.speak(utterance)
  }

  const handleVoiceInput = async (transcript) => {
    setLoading(true)
    setError(null)
    
    try {
      const response = await processVoiceQuery(transcript)
      setSchemeData(response.scheme)
      setAudioUrl(response.audioUrl)
      setCategory(response.category)
      setScreen('result')
    } catch (err) {
      console.error('Error processing voice:', err)
      setError('Maaf kijiye, kuch gadbad ho gayi. Phir se koshish karein.')
      
      // Clear error after 3 seconds
      setTimeout(() => setError(null), 3000)
    } finally {
      setLoading(false)
    }
  }

  const handleCategorySelect = async (selectedCategory) => {
    setLoading(true)
    setError(null)
    
    try {
      // Simulate getting scheme for selected category
      const response = await processVoiceQuery(`mujhe ${selectedCategory} ke baare mein batao`)
      setSchemeData(response.scheme)
      setAudioUrl(response.audioUrl)
      setCategory(selectedCategory)
      setScreen('result')
    } catch (err) {
      console.error('Error fetching scheme:', err)
      setError('Maaf kijiye, kuch gadbad ho gayi. Phir se koshish karein.')
      setTimeout(() => setError(null), 3000)
    } finally {
      setLoading(false)
    }
  }

  const handleBack = () => {
    if (screen === 'result') {
      setScreen('category')
    } else if (screen === 'category') {
      setScreen('start')
    }
    setSchemeData(null)
    setAudioUrl(null)
  }

  const goToCategory = () => {
    setScreen('category')
    // Play category selection audio
    const utterance = new SpeechSynthesisUtterance('Aap kis ke baare mein poochna chahte hain?')
    utterance.lang = 'hi-IN'
    utterance.rate = 0.9
    window.speechSynthesis.speak(utterance)
  }

  return (
    <>
      {screen === 'start' && (
        <StartScreen 
          onVoiceInput={handleVoiceInput}
          onSkipToCategory={goToCategory}
        />
      )}
      
      {screen === 'category' && (
        <CategoryScreen 
          onSelect={handleCategorySelect}
          onBack={handleBack}
        />
      )}
      
      {screen === 'result' && (
        <ResultScreen 
          category={category}
          scheme={schemeData}
          audioUrl={audioUrl}
          onBack={handleBack}
        />
      )}

      {/* Loading Overlay */}
      {loading && (
        <div className="loading-overlay">
          <div className="loading-spinner"></div>
          <div className="loading-text">Samajh raha hoon...</div>
        </div>
      )}

      {/* Error Toast */}
      {error && (
        <div className="error-toast">{error}</div>
      )}
    </>
  )
}
