AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sampark AI - Voice-first Government Scheme Assistant for India

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 512
    Environment:
      Variables:
        SCHEMES_TABLE: !Ref SchemesTable
        AUDIO_BUCKET: !Ref AudioBucket

Parameters:
  Stage:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod

Resources:
  # ============ API GATEWAY ============
  SamparkApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: sampark-ai-api
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE

  # ============ LAMBDA FUNCTION ============
  SamparkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sampark-ai
      CodeUri: ../backend/lambda/
      Handler: index.handler
      Description: Main Sampark AI Lambda handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SchemesTable
        - S3CrudPolicy:
            BucketName: !Ref AudioBucket
        - Statement:
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - transcribe:StartTranscriptionJob
                - transcribe:GetTranscriptionJob
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        QueryApi:
          Type: Api
          Properties:
            RestApiId: !Ref SamparkApi
            Path: /query
            Method: POST
        SchemeApi:
          Type: Api
          Properties:
            RestApiId: !Ref SamparkApi
            Path: /scheme/{category}
            Method: GET
        AudioApi:
          Type: Api
          Properties:
            RestApiId: !Ref SamparkApi
            Path: /audio/{schemeId}
            Method: GET
        TranscribeApi:
          Type: Api
          Properties:
            RestApiId: !Ref SamparkApi
            Path: /transcribe
            Method: POST
        HealthApi:
          Type: Api
          Properties:
            RestApiId: !Ref SamparkApi
            Path: /health
            Method: GET
        OptionsQuery:
          Type: Api
          Properties:
            RestApiId: !Ref SamparkApi
            Path: /query
            Method: OPTIONS
        OptionsScheme:
          Type: Api
          Properties:
            RestApiId: !Ref SamparkApi
            Path: /scheme/{category}
            Method: OPTIONS

  # ============ DYNAMODB TABLE ============
  SchemesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SamparkSchemes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: scheme_id
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: scheme_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: category-index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ============ S3 BUCKETS ============
  # Audio bucket for Polly output
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sampark-audio-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET]
            AllowedOrigins: ['*']
            MaxAge: 3600

  # Frontend hosting bucket
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sampark-frontend-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  # ============ CLOUDFRONT (Optional for production) ============
  # Uncomment for HTTPS and better performance
  # CloudFrontDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #         - DomainName: !GetAtt FrontendBucket.RegionalDomainName
  #           Id: S3Origin
  #           S3OriginConfig:
  #             OriginAccessIdentity: ''
  #       Enabled: true
  #       DefaultRootObject: index.html
  #       DefaultCacheBehavior:
  #         TargetOriginId: S3Origin
  #         ViewerProtocolPolicy: redirect-to-https
  #         ForwardedValues:
  #           QueryString: false

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${SamparkApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
  
  FrontendUrl:
    Description: Frontend S3 website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
  
  FrontendBucket:
    Description: S3 bucket for frontend deployment
    Value: !Ref FrontendBucket
  
  AudioBucket:
    Description: S3 bucket for audio files
    Value: !Ref AudioBucket
  
  SchemesTable:
    Description: DynamoDB table for schemes
    Value: !Ref SchemesTable
